services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    depends_on: [otel-collector]
    networks:
      - internal

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.111.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ${PWD}/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    networks:
      - internal

  chromadb:
    image: chromadb/chroma
    volumes:
      - ./chroma_data:/data
    ports:
      - "8000:8000"
    networks:
      - internal
    environment:
      - CHROMA_OPEN_TELEMETRY__ENDPOINT=http://otel-collector:4317/
      - CHROMA_OPEN_TELEMETRY__SERVICE_NAME=chroma
    depends_on:
      - otel-collector
      - zipkin

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: unless-stopped
    networks:
      - internal

#  backend:
#    build:
#      context: ../..
#      dockerfile: ai-agent-swagger/Dockerfile
#    image: ai-agent-swagger:latest
#    container_name: ai-agent-swagger
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATA_MONGODB_HOST: mongodb
#      SPRING_DATA_MONGODB_PORT: 27017
#      SPRING_DATA_MONGODB_USERNAME: admin
#      SPRING_DATA_MONGODB_PASSWORD: password
#      CHROMA_URL: http://chromadb:8000
#      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
#    depends_on:
#      - mongodb
#      - chromadb
#      - otel-collector
#    restart: unless-stopped
#    networks:
#      - internal
#
#  frontend:
#    build:
#      context: ../../react-frontend
#      dockerfile: Dockerfile
#    image: openapi-analyzer-frontend:latest
#    container_name: openapi-analyzer-frontend
#    ports:
#      - "3000:80"
#    depends_on:
#      - backend
#    restart: unless-stopped
#    networks:
#      - internal

networks:
  internal:

volumes:
  chroma_data:
  mongodb_data:
    driver: local